version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    env_file:
      - ./app/.env
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16.3
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./app/.env
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
